import { ReadinessAssessment } from './agents/synthesis-agent'

// ============================================================================
// Branding Configuration
// ============================================================================

export const INNOVAAS_BRANDING = {
  colors: {
    primary: '#F25C05', // Orange
    secondary: '#1D9BA3', // Teal
    darkBackground: '#111928',
    navBackground: '#1E232D',
    footerBackground: '#171B26',
    white: '#FFFFFF',
    lightGray: '#F5F5F5',
    midGray: '#777777'
  },
  logo: {
    path: '/designguide/innovaas_orange_and_white_transparent_bkgrnd_2559x594.png',
    width: 200,
    height: 46
  }
}

// ============================================================================
// Markdown Report Generation
// ============================================================================

export interface ReportMetadata {
  campaignName: string
  companyName: string
  facilitatorName: string
  generatedDate: string
  stakeholderCount: number
}

/**
 * Generate a comprehensive markdown report
 */
export function generateMarkdownReport(
  assessment: ReadinessAssessment,
  metadata: ReportMetadata
): string {
  const { overallScore, pillars, executiveSummary, keyThemes, contradictions, recommendations, stakeholderPerspectives } = assessment

  return `# Digital Transformation Readiness Assessment

**Campaign:** ${metadata.campaignName}
**Organization:** ${metadata.companyName}
**Facilitator:** ${metadata.facilitatorName}
**Assessment Date:** ${metadata.generatedDate}
**Stakeholders Interviewed:** ${metadata.stakeholderCount}

---

## Executive Summary

${executiveSummary}

---

## Overall Readiness Score

### **${overallScore.toFixed(1)} / 5.0**

${getMaturityLevelDescription(overallScore)}

---

## Readiness by Pillar

${pillars.map(pillar => `
### ${pillar.pillar} Pillar: **${pillar.score.toFixed(1)} / 5.0**

${pillar.dimensions.map(dim => `
#### ${dim.dimension}: ${dim.score.toFixed(1)} / 5.0
*Confidence: ${dim.confidence.toUpperCase()} | Priority: ${dim.priority.toUpperCase()}*

**Key Findings:**
${dim.keyFindings.map(f => `- ${f}`).join('\n')}

**Supporting Evidence:**
${dim.supportingQuotes.map(q => `> ${q}`).join('\n\n')}

**Gap to Next Level:**
${dim.gapToNext}

---
`).join('\n')}
`).join('\n')}

## Key Themes

${keyThemes.length > 0 ? keyThemes.map((theme, idx) => `${idx + 1}. **${theme}**`).join('\n\n') : '*No cross-cutting themes identified.*'}

---

## Contradictions & Gaps

${contradictions.length > 0 ? contradictions.map((contradiction, idx) => `${idx + 1}. **${contradiction}**`).join('\n\n') : '*No significant contradictions identified.*'}

---

## Strategic Recommendations

${recommendations.map((rec, idx) => `### ${idx + 1}. ${rec}\n`).join('\n')}

---

## Stakeholder Perspectives

${stakeholderPerspectives.map(sp => `
### ${sp.name} — ${sp.title}
**Role:** ${formatRoleType(sp.role)}

**Key Concerns:**
${sp.keyConcerns.length > 0 ? sp.keyConcerns.map(c => `- ${c}`).join('\n') : '*No specific concerns captured.*'}

${sp.notableQuotes.length > 0 ? `**Notable Quotes:**\n${sp.notableQuotes.map(q => `> "${q}"`).join('\n\n')}` : ''}

---
`).join('\n')}

---

## Maturity Level Reference

| Level | Name | Description |
|-------|------|-------------|
| 0 | Newcomer | Little awareness, manual processes, no strategy |
| 1 | Beginner | Initial awareness, pilot projects, limited scope |
| 2 | Intermediate | Defined processes, multi-department adoption, emerging best practices |
| 3 | Experienced | Integrated systems, organization-wide adoption, measurable impact |
| 4 | Expert | Optimized systems, industry best practices, strong competitive advantage |
| 5 | Leader | Industry-leading, ecosystem influence, transformative innovation |

---

## Assessment Methodology

This assessment was conducted using a structured multi-stakeholder interview approach informed by globally-recognized Industry 4.0 maturity frameworks. The methodology evaluates digital transformation readiness across three core pillars:

1. **Technology** (40% weight): Digital infrastructure, analytics capabilities, and cybersecurity resilience
2. **Process** (35% weight): Operations integration, supply chain connectivity, and innovation lifecycle
3. **Organization** (25% weight): Talent development and strategic governance

Each dimension is scored on a 0-5 maturity scale based on evidence from stakeholder conversations. Confidence levels indicate the strength of supporting data, and priority rankings guide recommended focus areas.

---

*Report generated by Innovaas FlowForge Assessment Platform*
*Date: ${metadata.generatedDate}*
`
}

// ============================================================================
// PDF Report Generation (React-PDF Structure)
// ============================================================================

/**
 * Generate PDF report data structure (to be rendered by @react-pdf/renderer)
 * This returns the structured data needed for PDF components
 */
export interface PDFReportData {
  metadata: ReportMetadata
  assessment: ReadinessAssessment
  branding: typeof INNOVAAS_BRANDING
  chartData: ChartData[]
}

export interface ChartData {
  type: 'pillar-scores' | 'dimension-heatmap' | 'priority-matrix'
  data: any
}

export function generatePDFReportData(
  assessment: ReadinessAssessment,
  metadata: ReportMetadata
): PDFReportData {
  return {
    metadata,
    assessment,
    branding: INNOVAAS_BRANDING,
    chartData: [
      {
        type: 'pillar-scores',
        data: assessment.pillars.map(p => ({
          name: p.pillar,
          score: p.score
        }))
      },
      {
        type: 'dimension-heatmap',
        data: assessment.pillars.flatMap(p =>
          p.dimensions.map(d => ({
            dimension: d.dimension,
            pillar: p.pillar,
            score: d.score,
            confidence: d.confidence,
            priority: d.priority
          }))
        )
      }
    ]
  }
}

// ============================================================================
// Helper Functions
// ============================================================================

function getMaturityLevelDescription(score: number): string {
  if (score < 1) return '**Newcomer** — The organization is in the early stages of digital transformation awareness with predominantly manual processes and limited strategic consideration.'
  if (score < 2) return '**Beginner** — Initial digital transformation initiatives are underway with pilot projects and exploratory implementations showing limited but growing impact.'
  if (score < 3) return '**Intermediate** — Digital capabilities are developing with defined processes, multi-department adoption, and emerging best practices beginning to take shape.'
  if (score < 4) return '**Experienced** — Digital transformation is well-established with integrated systems, organization-wide adoption, and measurable business impact alongside a culture of continuous improvement.'
  if (score < 5) return '**Expert** — The organization demonstrates optimized and adaptive digital systems, implementing industry best practices with strong competitive advantages and an innovation-driven culture.'
  return '**Leader** — Industry-leading digital capabilities with ecosystem-wide influence, transformative business model innovation, and recognition as a benchmark for others.'
}

function formatRoleType(roleType: string): string {
  const roleMap: Record<string, string> = {
    managing_director: 'Managing Director / Executive Leadership',
    it_operations: 'IT Operations Manager',
    production_manager: 'Production Manager',
    purchasing_manager: 'Purchasing Manager',
    planning_scheduler: 'Planning & Scheduling',
    engineering_maintenance: 'Engineering & Maintenance'
  }
  return roleMap[roleType] || roleType
}

// ============================================================================
// Export Utilities
// ============================================================================

/**
 * Format filename for report download
 */
export function generateReportFilename(
  companyName: string,
  campaignName: string,
  format: 'md' | 'pdf'
): string {
  const timestamp = new Date().toISOString().split('T')[0]
  const sanitizedCompany = companyName.replace(/[^a-zA-Z0-9]/g, '_')
  const sanitizedCampaign = campaignName.replace(/[^a-zA-Z0-9]/g, '_')

  return `${sanitizedCompany}_${sanitizedCampaign}_Assessment_${timestamp}.${format}`
}

/**
 * Get priority badge color based on priority level
 */
export function getPriorityColor(priority: string): string {
  const colorMap: Record<string, string> = {
    critical: INNOVAAS_BRANDING.colors.primary, // Orange
    important: INNOVAAS_BRANDING.colors.secondary, // Teal
    foundational: '#FFB347', // Warm accent
    opportunistic: INNOVAAS_BRANDING.colors.midGray
  }
  return colorMap[priority] || INNOVAAS_BRANDING.colors.midGray
}

/**
 * Get confidence badge color
 */
export function getConfidenceColor(confidence: string): string {
  const colorMap: Record<string, string> = {
    high: '#4CAF50', // Green
    medium: '#FFB347', // Warm accent
    low: '#FF9800', // Orange warning
    insufficient: INNOVAAS_BRANDING.colors.midGray
  }
  return colorMap[confidence] || INNOVAAS_BRANDING.colors.midGray
}

/**
 * Get score color based on value (0-5)
 */
export function getScoreColor(score: number): string {
  if (score >= 4) return '#4CAF50' // Green - Expert/Leader
  if (score >= 3) return INNOVAAS_BRANDING.colors.secondary // Teal - Experienced
  if (score >= 2) return '#FFB347' // Warm accent - Intermediate
  if (score >= 1) return '#FF9800' // Orange - Beginner
  return INNOVAAS_BRANDING.colors.midGray // Gray - Newcomer
}
